METHOD SOP_ITEMSET_GET_ENTITYSET.

 DATA(LS_SOPNUM) = IT_KEY_TAB[ NAME = 'Sopnum' ]-VALUE.
 DATA(LS_CTRYCODE) = IT_KEY_TAB[ NAME = 'Ctrycode' ]-VALUE.

 IF LS_SOPNUM IS NOT INITIAL.
  SELECT *
   FROM ZVBSD0011 AS A
   WHERE A~SOPNUM = @LS_SOPNUM
    AND A~CTRYCODE = @LS_CTRYCODE
   INTO TABLE @ET_ENTITYSET.
 ELSE.
  SELECT * FROM ZVBSD0011 INTO TABLE @ET_ENTITYSET.
 ENDIF.

  IF SY-SUBRC <> 0.
   RAISE EXCEPTION TYPE /IWBEP/CX_MGW_BUSI_EXCEPTION.
   RETURN.
  ENDIF.
 ENDMETHOD.