METHOD SOP_HEADERSET_UPDATE_ENTITY.

  DATA(LS_SOPNUM) = IT_KEY_TAB[ NAME = 'Sopnum' ]-VALUE.
  DATA(LS_CTRYCODE) = IT_KEY_TAB[ NAME = 'Ctrycode' ]-VALUE.

  DATA LS_DATA TYPE ZTBSD0010.

  IO_DATA_PROVIDER->READ_ENTRY_DATA(
   IMPORTING
    ES_DATA = LS_DATA
  ).

  UPDATE ZTBSD0010
   SET Appr = @LS_DATA-APPR,
     Status = @LS_DATA-STATUS,
     Rejreason = @LS_DATA-REJREASON
  WHERE Sopnum = @LS_SOPNUM
   AND Ctrycode = @LS_CTRYCODE.

  IF SY-SUBRC <> 0.
   RAISE EXCEPTION TYPE /IWBEP/CX_MGW_BUSI_EXCEPTION.
  ENDIF.

 ENDMETHOD.